version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        # [Choice] Node.js version: 14, 12, 10
        VARIANT: 14
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - ..:/workspace:cached
      # Use existing SSH keys
      - ~/.ssh:/home/node/.ssh

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    links:
      - db
      - redis

    env_file:
      - ../.env

  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
      - ../overflow-backend/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - ../.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_INITDB_DATABASE
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379

volumes:
  mongodb-data: